### ISSUE TITLE
Resolve conflict between global and proposal-specific delegations to same delegate

### ISSUE THREAD

**Issue by jinjagit** [liquidvotingio/api#125]
Following #109, it is possible to create both a global and proposal-specific delegation for the same delegator/delegate pair, but this is not the desired behaviour.  

Specifically we wish to treat 2 separate cases:  

1. If a proposal-specific delegation creation is attempted, when an existing global delegation for same delegator/delegate pair exists, the new delegation creation should be rejected.  
2. If a global delegation is created, then any existing proposal-specific delegations for same delegator/delegate pair should be deleted.

**Comment by oliverbarnes** [comment]
👌 well described

**Comment by jinjagit** [comment]
Note to self: There are 3 skipped tests in `test/liquid_voting/delegations_test.exs` that need addressing in this issue + probably need to create some absinthe tests to go with this issue and the cases it covers.

**Comment by oliverbarnes** [comment]
Trying to summarize delegation constraints, for sanity :sweat_smile:. 

**At any given moment a given participant can only have, as a delegator:**
- 1 global delegation
- multiple proposal-specific delegations, as long as:
  - they're to delegates other than the global delegate
  - and each delegation has a different proposal

**At no point can a delegator have:**
- two global delegations
- a global delegation and a proposal-specifc delegation to the same delegate
- two proposal-specific delegations with the same proposal url

**Comment by jinjagit** [comment]
Closing this, as covered by #132 and #133, except for issue raised in #137 (which is now in progress)
