### ISSUE TITLE
Prevent duplicate proposal-specific delegations 

### ISSUE THREAD

**Issue by jinjagit** [liquidvotingio/api#126]
Following #109, it is (will be) possible to create duplicate proposal-specific delegations.  

This should be prevented. The simplest solution may be to use a unique index of org/delegator/delegate/proposal_url.

**Comment by oliverbarnes** [comment]
This is better covered in #109, as it'll be a regression otherwise.

#125 is new functionality so it makes sense to implement separetely

**Comment by jinjagit** [comment]
OK, I'll delete this issue and cover it in #109
