### ISSUE TITLE
Prevent duplicate delegations when created using participant ids

### ISSUE THREAD

**Issue by jinjagit** [liquidvotingio/api#128]
We can create a 2nd (or more) global or proposal-specific delegations for same delegator, when `create_delegation/1` is called with participant ids in the args. Only one such delegation should exist, and duplicate creation / entries should be prevented.

**Comment by jinjagit** [comment]
On further investigation it appears that now it is possible (again) to create a 2nd global or proposal specific delegation for _different_ delegates (same delegator) _and_ for the same delegate. This means we seem to have lost the gains of #112. More concerningly, tests are not picking this up - perhaps because we removed the list_delgations count from the assertions + I chose not to match the delegation ids in the tests due to the issue of the changeset generating a new uuid regardless of whether it is involved in an update or insert action.  
Thus we now need to ensure:
1. Only one global delegation per delegate  
2. Only one proposal-specific delegation per delegate / per proposal  
I have edited the title to reflect this regression.

**Comment by oliverbarnes** [comment]
Ah! I didn't know the id changed on updates, my bad on not spotting that in the reviews either. That sounds like it's the culprit indeed.

Might be good to double check participant upserts as well, the id shouldn't change there either

**Comment by jinjagit** [comment]
> Ah! I didn't know the id changed on updates, my bad on not spotting that in the reviews either. That sounds like it's the culprit indeed.
> 
> Might be good to double check participant upserts as well, the id shouldn't change there either

Yeah, but I'm wrong. I just added id assertions to tests and they still pass! Even though app is merrily creating new global delegations for same delegate, for example... tests still report original delegation was updated.

**Comment by jinjagit** [comment]
OK, I think I understand this now:  
Testing `create_delegation` via iex console, duplicate delegations are possible, when creating delegations using _**participant IDs**_.  
The tests, however, only test `upsert_participant`, which is only called by the `create_delegations` function that matches with _**emails**_.  
Thus #112 probably successfully upserts duplicate delegations created with emails, but does not deal with createDelegations using participant ids. I think I erroneously assumed we did not do this via absinthe (but the fields are totally there as option in the mutation)  
Maybe start by switching the tests back to testing `create_delegation`? Or add very similar tests that go through 'create_delegation`?

**Comment by oliverbarnes** [comment]
Summing up finds from pairing on this:

The data layer `Delegations.create_delegation/1` function clause that matches participant ids only creates delegations - it doesn't upsert like the function with the clause matching emails that precedes it:

```
def create_delegation(%{delegator_email: _, delegate_email: _} = args) do
...
    attrs
    |> Map.put(:delegator_id, changes.delegator.id)
    |> Map.put(:delegate_id, changes.delegate.id)
    |> upsert_delegation()
...
end

def create_delegation(attrs) do
  %Delegation{}
  |> Delegation.changeset(attrs)
  |> Repo.insert()
end
```

So this function needs to be updated to use upserts as well, only with participant ids instead.

**Comment by jinjagit** [comment]
I think this can be closed now, as it is no longer possible to create duplicate delegations (with ids or emails), following resolution of #137. The issue of whether we should enable creation of new participants using only ids is covered separately in #130.
