### ISSUE TITLE
Change multi-clause create_delegation/1 to use all validations when attrs include participant_ids

### ISSUE THREAD

**Issue by jinjagit** [liquidvotingio/api#137]
Currently, absinthe will accept either emails or participant ids in createDelegation mutation, but only the create_delegation/1 clause that matches the emails case will subsequently apply a range of validations and conflict resolutions to the delegation creation process.  

A (simple) refactoring of the clauses should accommodate both cases.  

May well also require a number of new related tests.

**Comment by jinjagit** [comment]
This will probably also resolve #128

**Comment by oliverbarnes** [comment]
Sounds good. Just a quick pedantic clarification - by definition refactors don't change functionality. It's only about reorganizing code, while keeping the system working the same as before.

**Comment by jinjagit** [comment]
> Sounds good. Just a quick pedantic clarification - by definition refactors don't change functionality. It's only about reorganizing code, while keeping the system working the same as before.

True. Title changed
