### ISSUE TITLE
Add Participant UUID

### ISSUE THREAD

**Issue by oliverbarnes** [liquidvotingio/api#14]
#12 adds the option to create a vote and delegation using participant emails instead of id.

Later on email identification won't be the only option, as there'll be authentication by other means - for example, by [Blockstack ID](https://docs.blockstack.org/browser/ids-introduction.html).

Both auth and user management will be done by a separate service, so there should be a unique cross-service id to identify them.

**Comment by oliverbarnes** [comment]
@jinjagit ultimately the task is adding a new "uuid" field to the "participants" table, and this field would be of Ecto.UUID type. You'll have to create an ecto migration for it

https://hexdocs.pm/ecto/Ecto.UUID.html

**Comment by jinjagit** [comment]
understood. will do.
