### ISSUE TITLE
Proposal delegation creation should be prevented when vote for same participant (delegator) & proposal exists

### ISSUE THREAD

**Issue by jinjagit** [liquidvotingio/api#160]
Currently, the following sequence of actions fails, when it should succeed OR be halted (by an error - cannot create delegation due to vote for same proposal + delegator existing) at step 2.:  
```
Note: All actions in this example involve the same specific proposal.

1. createVote  
2. createDelegation (delegator = participant who just voted)
3. deleteDelegation (delete delegation just created)
4. createVote (try to create same vote as initial createVote)
=> "Could not create vote / Participant id has already been taken"
```
  
Not yet manually tested in case where no vote created first (but I suspect this does not fail and may already be covered by tests), nor manually tested with global delegation case.

**Comment by oliverbarnes** [comment]
Does the original vote created on 1. get deleted at least?

**Comment by jinjagit** [comment]
No. At step 2, when creating a (conflicting) delegation, the vote is not deleted.

**Comment by jinjagit** [comment]
Don't we want the existing vote to prevent a subsequent conflicting delegation creation (return an error), rather than delete the existing vote?

**Comment by oliverbarnes** [comment]
Ah, you're right, the delegation shouldn't override the vote. 

But then I'd expect `2` here should fail with that error, and `3` shouldn't be possible because the delegation shouldn't exist. 

And I'd expect `4` to error, but perhaps with a different message - "vote already cast" or something equivalent?

**Comment by jinjagit** [comment]
Yeah, I had forgotten the override priorities, too. It should, therefore, fail at step 2, yes.  

Yes, the  error message at 4 should be more specific, and perhaps this is a sign that this case is not well handled either.

**Comment by oliverbarnes** [comment]
What happens on step 2?

**Comment by jinjagit** [comment]
Step 2 = delegation is created , step 3 = delegation deleted
