### ISSUE TITLE
Pass on and use organization_id to filter db queries in children functions of create_delegation/1

### ISSUE THREAD

**Issue by jinjagit** [liquidvotingio/api#164]
`organization_id` (in args) isn't passed from `delegations.ex/create_delegation/1` -> `upsert_delegation/1` -> `check_vote_conflict/2` -> `get_vote_by_participant_id/2`, and thus all the db queries that those subsequent functions use will also search through entries for organizations other than the one in play at the time. 

These should all use `organization_id` to filter queries.

**Comment by oliverbarnes** [comment]
> I have not been passing

_We_ have not been passing ;) or even better,  impersonal passive "organization_id wasn't passed into...". 

Let's have comms reflect collective code ownership, and keep reporting of issues blameless. Same for PRs

**Comment by jinjagit** [comment]
Sure. I can edit and delete your comment (& this). Is that OK?

**Comment by oliverbarnes** [comment]
👍 yeah, that's fine! I'm going ahead and doing it now
