### ISSUE TITLE
Return a votingResult on CreateDelegationMutation

### ISSUE THREAD

**Issue by oliverbarnes** [liquidvotingio/api#189]
Brought up by @davefrey: 

CreateDelegationMutation returns a boolean; all the other mutations return a votingResult, let's make that consistent

**Comment by jinjagit** [comment]
Is this done now? (I have a feeling it is)

**Comment by davefrey** [comment]
I just tested, and for the `CreateDelegationMutation` described in `client.rb`
* the api returns the id of the delegation
```
(byebug) response.data.create_delegation
#< id="8fd5b29c-397a-4b89-b6c7-3a7325194c02">
```
* the ruby `Client.create_delegation` then, in the absence of errors, systematically returns
```
true
```

Both the api and the ruby client should be returning a `votingResult`, as do the other three mutations.

**Comment by davefrey** [comment]
Everything can be handled on the module side, I'll close this issue. 
Possibly there is api return value normalisation to be done in `ruby-client`, I'll add an issue if so.
See liquidvotingio/decidim-module-liquidvoting#94 to track the resolution in that repo.
