### ISSUE TITLE
Add smoke test at the end of CI

### ISSUE THREAD

**Issue by oliverbarnes** [liquidvotingio/api#23]
To ensure the live API is up and running after updating

**Comment by oliverbarnes** [comment]
- create test org on auth service
- send create delegation request and then a vote from a delegate
- teardown with delegation and vote deletion (need to add deletion to schema/resolvers)

**Comment by niklaslong** [comment]
Unless it's tricky to do, I'm thinking it might be worth getting this done fairly quickly?

**Comment by oliverbarnes** [comment]
I think it's fairly straight forward, just wasn't sure on the tool. We need to submit requests and then assert on the response (200 OK and non-error payloads). I was considering [k6](https://k6.io/), a load testing tool.

**Comment by niklaslong** [comment]
K6 looks great! 

Just putting this here for future reference: https://k6.io/docs/test-types/smoke-testing

> teardown with delegation and vote deletion (need to add deletion to schema/resolvers) 

Deletion seems to have been implemented: 
https://github.com/liquidvotingio/api/blob/9aac7ef5f797a8bb3051e09cac898c389546dc45/lib/liquid_voting_web/schema/schema.ex#L68-L74

https://github.com/liquidvotingio/api/blob/9aac7ef5f797a8bb3051e09cac898c389546dc45/lib/liquid_voting_web/schema/schema.ex#L86-L94

**Comment by oliverbarnes** [comment]
Nice! I hadn't seen that doc yet. And yes, we do have deletion now - this is definitely good to go 🚢
