### ISSUE TITLE
Do we want delegations to override votes?

### ISSUE THREAD

**Issue by oliverbarnes** [liquidvotingio/api#39]

**Comment by jinjagit** [comment]
Is this still an issue? Doesn't a vote override a vote already?

**Comment by oliverbarnes** [comment]
Not sure. Do we have a passing test for it?

**Comment by jinjagit** [comment]
I was thinking the same thing. I'll check.

**Comment by jinjagit** [comment]
You are quite correct. A delegation does not override a vote.  

To reproduce:
```
org = Ecto.UUID.generate()
attrs = %{name: "Alice", email: "alice@gmail.com", organization_id: org}
Voting.create_participant(attrs)

attrs = %{yes: true, weight: 1, participant_id: <insert id of Alice>, proposal_url: "https://p.com/1", organization_id: org}
Voting.create_vote(attrs)

attrs = %{name: "Bob", email: "bob@gmail.com", organization_id: org}
Voting.create_participant(attrs)

attrs = %{delegator_id: <insert id of Alice>, delegate_id: <insert id of Bob>, organization_id: org, proposal_url: "https://p.com/1"}
Delegations.create_delegation(attrs)

attrs = %{yes: false, weight: 1, participant_id: <insert id of Bob>, proposal_url: "https://p.com/1", organization_id: org}
Voting.create_vote(attrs)

VotingResults.calculate_result!("https://p.com/1", org)

=> against: 2, in_favor: 1
```
(`in_favor` should be 0, if the vote was overriden by the delegation)

**Comment by jinjagit** [comment]
Do we also want the reverse? A vote should override a delegation?

**Comment by oliverbarnes** [comment]
My impression is it already does, but don't trust my memory :) and we should also have tests for it, of course

**Comment by jinjagit** [comment]
You are correct. I just tested that a vote overrides a delegation, using the iex console + we have a test: `test "create_vote/1 deletes previous delegation by participant if present"`
