### ISSUE TITLE
Update all results that may be affected by deleting a global delegation?

### ISSUE THREAD

**Issue by oliverbarnes** [liquidvotingio/api#44]
Deletion of delegations is implemented by #43. 

Deleting a delegation for a specific proposal updates the voting result for that proposal.

Current deletion of global delegation doesn't update any results, as the ramifications have to be thought out carefully. There could be many results affected, and finding them could be a resource intensive procedure.

**Comment by oliverbarnes** [comment]
Come to think of it, results affected by the creation of global delegations also need to be updated

**Comment by jinjagit** [comment]
> Come to think of it, results affected by the creation of global delegations also need to be updated

#52 addressed the recalculation of any related results on global delegation creation.
