### ISSUE TITLE
Rename attributes in `VotingResult` to avoid confusion with an individual `Vote`.

### ISSUE THREAD

**Issue by davefrey** [liquidvotingio/api#46]
The `VotingResult` is meant to be a _tally_ of votes for a proposal. Currently, the tally attributes are `yes` and `no`, which for me is confusing: while `VotingResult.yes` is a sum, `Vote.yes` is a boolean.

I suggest instead `votes_for` and `votes_against`: these are explicitly tallies, without interpreting the `VotingResult` context. For an individual `Vote`, `yes` remains the best attribute name.

This change should include the database columns and all mentions of the attributes. It would also require superficial rename changes in other repos:
```
liquidvotingio/api
liquidvotingio/ruby-client
liquidvotingio/deployment
liquidvotingio/liquidvotingio.github.io
```
This one is mothballed:
~~liquidvotingio/liquid-voting-admin~~

**Comment by oliverbarnes** [comment]
Agreed 👍. Want to send in the PRs?

Don’t worry about admin though, it’s mothballed for now

**Comment by davefrey** [comment]
Agreed to use `in_favor` and `against` as the new names.

**Comment by davefrey** [comment]
The last PR for this ticket will be in liquidvotingio/liquidvotingio.github.io but I can't push, could you check if I have write on that repo? Thanks! @oliverbarnes

**Comment by oliverbarnes** [comment]
Added!

**Comment by davefrey** [comment]
Okay I think everything is here now. If you're good, you can merge the 4 PRs
