### ISSUE TITLE
Understand `mix.lock` format differences between devs

### ISSUE THREAD

**Issue by davefrey** [liquidvotingio/api#53]
A recent PR #49 from @davefrey introduced wholesale changes to the `mix.lock` file: every dependency tuple had a new hash on the end. Those were backed out but to avoid future back-and-forth churn we should avoid format noise (so we can see actual dependency updates).

I suspect a difference in elixir/mix/hex versions, but I'm new to elixir.

**Comment by davefrey** [comment]
I'm not finding much on the spec of the `mix.lock` file; I did see a [2017 conversation](https://elixirforum.com/t/mix-lock-being-rewritten-with-and-then-without-hexpm/4703/3) about "hexpm" being added to the end of each dependency.

@oliverbarnes what do you see with `mix local.hex`? I get
```
api git:(master) mix local.hex
Found existing entry: /Users/davefrey/.mix/archives/hex-0.20.5
Are you sure you want to replace it with "https://repo.hex.pm/installs/1.10.0/hex-0.20.5.ez"? [Yn]
```
which seems to be the latest
I'm curious if just getting us both the the latest `hex` will put us back in sync.

**Comment by oliverbarnes** [comment]
I get the same thing 🤷 Maybe ask on https://elixirforum.com/ ?

**Comment by oliverbarnes** [comment]
```
mix -v
Erlang/OTP 22 [erts-10.7] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]

Mix 1.10.2 (compiled with Erlang/OTP 22)
```

**Comment by davefrey** [comment]
Not much coming back on elixirforum, someone confirmed no spec for the file. I'm tempted to just "up" the lock file in what I assume is the new format, so that we can then update dependencies and have useful diffs going forward. I'll push that and we can roll back and find another solution if we're thrashing on lock formats.

I notice it's `mix deps.get` that triggers the new format. If we're both on the same mix/hex, I'm assuming if you run that you also get new hashes on each line?

**Comment by oliverbarnes** [comment]
👍 just pulled latest and ran `mix deps.get`, no conflicts. Didn't update the hashes that were committed.
