### ISSUE TITLE
Run formatter

### ISSUE THREAD

**Issue by niklaslong** [liquidvotingio/api#59]
I notice we're not using `mix format`? It might also be a good idea to check it on CI with `mix format --check-formatted`?

**Comment by oliverbarnes** [comment]
Agreed, this is long overdue. I don’t have an opinion yet on a style guide follow, I’m ok going with the one you’ve used the most. 

Want to fork and submit a PR with the CI update and style fixes? Hopefully the code state is not too bad 😅

I’d try to break up changes in granular commits so as to not have one commit touching a lot of the codebase.

(Next week I’ll add you up as a collaborator on all repos so you don’t have to do it from a fork)

**Comment by niklaslong** [comment]
Ah opened #60 as you wrote the above 😁 

I think doing it incrementally is a good idea! #60 just runs the formatter and I'll submit another PR for the style changes (I'll fix the most obvious for now)

**Comment by oliverbarnes** [comment]
Sounds good. I’ll then merge the PR with the fixes first and the CI update
after it, so the CI doesn’t break
