### ISSUE TITLE
Make :uuid primary field for Participant

### ISSUE THREAD

**Issue by oliverbarnes** [liquidvotingio/api#68]
After #67 is done

**Comment by niklaslong** [comment]
Was your intention to use the UUID only externally or also internally for the assocs?

**Comment by oliverbarnes** [comment]
For both, in principle. Primary id for each resource, association id, and
external reference. But am open to adding an external_uuid that could be
mutable (for frontends, for example) at some point, nothing certain yet.
Thoughts?

**Comment by jinjagit** [comment]
By "primary field" are you referring to an Absinthe, GraphQL, or other specific type of field, or a more generic meaning?
(I am assuming you do not men "primary key")

**Comment by niklaslong** [comment]
> Thoughts?

I think simply replacing the primary key for `id` with the `uuid` for now is the simplest. Whether we choose to use another externally will be highly dependant on how we handle the mapping of external users to our internal representation of them .

**Comment by oliverbarnes** [comment]
> By "primary field" are you referring to an Absinthe, GraphQL, or other specific type of field, or a more generic meaning?
> 
> (I am assuming you do not mean "primary key")

Good question - I mean for all of the above. Primary key and id for reference internally and externally

**Comment by jinjagit** [comment]
So, make uuid the primary key and primary reference field across the api. Eventually.

**Comment by oliverbarnes** [comment]
Exactly. And come to think of it, this probably needs to be coordinated across the other resources (votes, delegations, results), so there are parallel PRs for each, and changes are merged and deployed around the same time and the API is kept consistent

**Comment by jinjagit** [comment]
closed, as covered by [#76](https://github.com/liquidvotingio/api/pull/76)
