### ISSUE TITLE
Teardown of data after smoke and acceptance tests

### ISSUE THREAD

**Issue by oliverbarnes** [liquidvotingio/api#88]
After #87 it's clear not all data can be setup and teardown through graphql requests, so let's try another path.

One might be to follow [what we do with database migrations](https://github.com/liquidvotingio/api/blob/master/lib/liquid_voting/release.ex#L4-L12), which is to call a special release function after these external tests run.

cc @jinjagit

**Comment by oliverbarnes** [comment]
These release hooks can be used with a container eval (see the prod migration runbook), and from a github action:

```
kubectl exec -ti pod/$pod \
--container api-container \
-- /opt/app/bin/liquid_voting \
eval "LiquidVoting.Release.migrate"
```

**Comment by jinjagit** [comment]
So I could use something like this, with LiquidVoting.Release.teardown, for example, where teardown/0 calls my mix task?

Oliver  4 minutes ago
yes, but you wouldn't need a mix task in this case because LiquidVoting.Release already has access to the environment

**Comment by jinjagit** [comment]
I was thinking it would be useful to leave as a mix task, as then it can also be used locally in dev env (although mix.ecto reset kind of achieves the same thing)

**Comment by oliverbarnes** [comment]
It'd only make sense to use a mix task if you were logged-in to the server instance and mix were available to interact with the app there. In this case, a github action will be calling a remote server instance (a container in a kubernetes pod) and asking it to execute a dedicated hook that has access to the app environment. And within that hook, mix isn't available (it's already in a phoenix process), and it'd just add a lot of overhead anyway.

locally, yeah, a mix ecto.reset would suffice, since there's no problem wiping out the data. On the server of course we're only deleting data scoped to an organization id.
