### ISSUE TITLE
Add validation(s) to prevent multiple delegations by same delegator

### ISSUE THREAD

**Issue by jinjagit** [liquidvotingio/api#91]
1. At present, it is possible to create 2 or more delegations for the same delegator (global and/or proposal specific). This will add an extra vote per delegation (not desirable beyond the first delegation). We need therefore, to validate "delegator is not already the delegator for a similar delegation (global or proposal-specific)' before creating a delegation. This validation should also prevent creation of proposal specific delegations for a delegator who is already a global delegation delegator.

2. At present, it is possible to create a circular delegation, where A delegates to B, and B delegates to A. If anyone in the circular delegation chain votes, the votes added to the result reflect the number of participants in the chain, and the delegation of the voter is deleted (all desirable behaviour). It is unlikely that anyone in such a chain *would* vote, however, since they have all delegated their votes.   

Note that such chains might loop back to a point other than the end of the chain: e.g. A -> B -> C -> B  
The creation of an error message that explains the reason for rejecting such a delegation in simple enough language might also be challenging.

**Comment by oliverbarnes** [comment]
👍 Thanks for this, we definitely need to improve validations around the many delegation permutations. 

Do you mind breaking the points raised into separate issues? They're discrete pieces of work, I think

**Comment by jinjagit** [comment]
I'll close this issue and create 2 new issues, since it might be confusing if I leave one issue here alongside your comment.
