### ISSUE TITLE
Prevent circular delegations

### ISSUE THREAD

**Issue by jinjagit** [liquidvotingio/api#93]
At present, it is possible to create a circular delegation, where A delegates to B, and B delegates to A. If anyone in the circular delegation chain votes, the votes added to the result reflect the number of participants in the chain, and the delegation of the voter is deleted (all desirable behaviour). It is unlikely that anyone in such a chain would vote, however, since they have all delegated their votes.  

Note that such chains might loop back to a point other than the end of the chain: e.g. A -> B -> C -> B
The creation of an error message that explains the reason for rejecting such a delegation in simple enough language might also be challenging.

**Comment by oliverbarnes** [comment]
Yeah, great points. Personally I'd like to be at least warned I might be delegating to somebody who's already delegating to me. Even being blocked from delegating altogether if I'm already a delegate for that person might make sense.

About the second scenario (A -> B -> C -> B), it's really still the above: B <-> C. But A -> B -> C -> A is a problem, we'll have to traverse the delegation tree to see find these deep loops.

**Comment by oliverbarnes** [comment]
https://liquid-democracy-journal.org/issue/3/The_Liquid_Democracy_Journal-Issue003-02-Circular_Delegations_-_Myth_or_Disaster.html

**Comment by jinjagit** [comment]
Interesting article. Seems to imply a counter-argument: Even if such a chain results in no votes cast for members of the chain (due to all believing a delegate will do this), this is preferable to precluding a delegation because the participant who wishes to be delegator has been 'made' a delegate in what would become a circular chain (not necessarily a choice of the participant who is delegate).  
I wonder, however, if this approach (allowing circular delegations) might be open to manipulation (in the case where the process is transparent enough to look for such chains)?

**Comment by oliverbarnes** [comment]
A couple of other things to consider also:

- A delegator shouldn't expect a delegation will necessarily guarantee a vote at the end. There's always a chance a delegate will simply abstain.
- These scenarios all might change depending on whether the delegation trees are visible or not, which is an open question and might be better left for a platform to decide.

I'm leaning towards just waiting until any problems actually do come up (or not) before tackling them. Let's wait until we have some actual users and minimally complex delegations :) Come to think of it, I remember coming across this a while back and arriving at the same conclusion, based on liquidfeedback's experience.

What do you think?

**Comment by jinjagit** [comment]
Yes, the more I think about it, the more I think it depends on transparency to the participant. Leave this for now seems wise, especially as we have more basic delegation issues to consider first.
